version: "3.9"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend
      - frontend
    networks:
      - transactions_network

  mongo:
    image: mongo:6.0
    container_name: mongo
    # ports:
    #   - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_DATABASE: arthaDB
    volumes:
      - mongo_data:/data/db
    networks:
      - transactions_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend_server
    # ports:
    #   - "5173:80"  # maps Nginx inside the container (port 80) to localhost:5173
    expose:
      - "80"
    networks:
      - transactions_network
    restart: always

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend_server
    command: sh -c "node src/index.js"
    env_file:
      - "./server/.env"
    environment:
      PORT: 5000
      MONGO_URL: mongodb://mongo:27017/arthaDB
      JWT_SECRET_KEY: ARTHA_MINDFULNESS
      FRONTEND_URL: http://nginx:80
    depends_on:
      - mongo
    expose:
      - "5000"
    networks:
      - transactions_network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/auth/login"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  mongo_data:

networks:
  transactions_network:

